### ISSUE TITLE
Reconciling vs Stalled overlap

### ISSUE THREAD

**Issue by seaneagan** [kubernetes-sigs/cli-utils#167] opened 2020-05-11 19:03 UTC
The `Reconciling` condition seems to encode whether the controller is currently still attempting to reconcile the resource (at its current observed generation), i.e. `Reconciling==False` (done), `Reconiling !=False` (potentially not done), and doesn't say anything about success/failure. The "Stalled" terminology seems to have some overlap with this, where `Stalled==True` (done and failed), `Stalled==False` (not done and/or not failed). It seems normalizing to have one condition signal "done / not done reconciling" and another to signal "error(s) encountered" could be:

1. more expressive, currently the "errors encountered, but not done trying" state cannot be expressed. This could be used to display helpful information during wait operations as to current progress / lack thereof, which can be used by a human to cancel a doomed wait operation, or by a client which times out to provide more information for debugging.
2. less confusing / error prone, currently `Stalled==True && Reconciling==True` seems to be invalid.

For example instead of "Stalled" it could be "ErrorEncountered" or just "Error". The condition Reason/Message could be used to give details of the error(s). Ideally multiple errors could be signaled independently via adding some metadata to conditions, e.g. `error: true` or `severity: error` as mentioned in https://github.com/kubernetes/community/pull/4521#discussion_r415988746, but that may be more difficult to gain traction on.

**Comment by seaneagan** [comment] 2020-05-12 14:41
So I guess this issue is really just about an ability to signal temporary errors via the kstatus library (1. above). It could be solved additively on top of the `Stalled` condition, but was just checking on the possibility of solving it with a smaller API surface via an alternative to the `Stalled` condition. Point 2. above is pretty easy to resolve by having some utility code to manage `Stalled` and `Reconciling` to keep them consistent.

**Comment by mortent** [comment] 2020-05-12 20:39
The intention of the `Stalled` condition is to signal that the controller has not made the expected progress towards reconciling the desired state with the actual state. This can be caused by an actual error or it can be due to a timeout. So the interpretation of it should be something like :

`there seems to be something wrong, so someone should take a look. It might also be that something is just slow, so it might also resolve itself after some period of time`

We did consider naming this condition something like "Failed" or "Error", but decided those seem to suggest a final state. In reality, most processes in Kubernetes keep retrying forever and there might be automation that will resolve things over time. It is hard in most cases to distinguish "slow" from "doomed". So I think the `Stalled` condition is pretty much what you suggested with the `ErrorEncountered` or `Error` conditions, but it doesn't try to distinguish between permanent and transient errors.

We are keeping an eye on https://github.com/kubernetes/community/pull/4521, and it will almost certainly lead to some adjustments in the kstatus library if/when it is merged. Most importantly, it changes the suggest naming scheme of conditions away from using "abnormal-true" polarity. So we probably want to come up with a new set of conditions that are aligned with the new recommendations (but still keep support for the current recommendations).

**Closed** 2020-10-09 22:37 UTC
Labels: lifecycle/rotten
